version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://192.168.50.207:11434  # Updated to correct IP address
    volumes:
      - open-webui:/app/backend/data
    restart: always

volumes:
  open-webui:
