services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker/sonarr:/config
      - /media/TV:/tv
      - /srv/docker/sabnzbd/downloads:/downloads
    ports:
      - 8989:8989
    dns:
      - 4.2.2.2
    networks:
      - media_default
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker/radarr:/config
      - /media/Movies:/movies
      - /srv/docker/sabnzbd/downloads:/downloads
    ports:
      - 7878:7878
    dns:
      - 4.2.2.2
    networks:
      - media_default
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker/prowlarr:/config
    ports:
      - 9696:9696
    dns:
      - 4.2.2.2
    networks:
      - media_default
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/docker/sabnzbd:/config
      - /srv/docker/sabnzbd/downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    dns:
      - 4.2.2.2
    networks:
      - media_default
    restart: unless-stopped

networks:
  media_default:
    external: true
